title: My blog
author: Mapachana
email: sk.lofa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site where I can start testing things

twitter_username: Mapachana
github_username:  Mapachana

#sass:
#    style: compressed
