title: My blog
author: Mapachana
email: sk.lof@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site where I can test things

twitter_username: jaja
github_username:  Mapachana

sass:
    style: compressed
